### PR TITLE
Merge branch 1.5.x to master

### PR DESCRIPTION
**Pull request by brabenetz**
There are multiple fixes in Branch 1.5 which I merged into the master (plus fixing optional dependency to guava):

-----------------------------------
**Compile Error with JDK5:**
ma.glasnost.orika.impl.generator.VariableRef line 56 contains the call Collections.newSetFromMap(..,) which only exists since 1.6: 
https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#newSetFromMap%28java.util.Map%29

I simply updated the maven-compiler-plugin in the pom.xml line 315&316 to 1.6 (because there is no open jdk-5 issue obviously no-one use orika with jdk5):
https://github.com/brabenetz/orika/commit/c360935c779aba80cb9e02e0522eaa017eaf1a30

-----------------------------------
**Eclipse Settings folder ".settings" removed:**
most likely committed accidentally.

-----------------------------------
**Travis-CI:**
I'm not sure what the difference of the Travis-CI instances are, but I suppose that my instance is a newer container-based instance:
My Travis-CI instance: https://travis-ci.org/brabenetz/orika/builds
Orikas Travis-CI instance: https://travis-ci.org/orika-mapper/orika/builds

The Results often differ in the results.

At least for the container-based Travis-CI the following changes are required:
 - limit maven-surefire-plugin in memory: because the container based Travis-CI has only 3 GB ram which is less then the default VM. And some Memory-Consumption-Tests fills the memory with garbage to force the release of weak references.
 - set "sudo: false" in ".travis.yml" because container based Travice-CI doesn't allow sudo.

I also added openjdk6 to the build, but I removed it again since it appears to be unstable on travisCI (see #159).

-----------------------------------
**Fix Optional dependency to Guava:**
ma.glasnost.orika.metadata.Type and ma.glasnost.orika.impl.DefaultConcreteTypeMap uses the guva class ImmutableMap which make Guava not optional anymore.
I refactored it with Collections.unmodifiableSet(...) and Collections.unmodifiableMap(...).
The dependency commes in with the last merge of #157 and #155: 
https://github.com/orika-mapper/orika/pull/155
https://github.com/orika-mapper/orika/pull/157

-----------------------------------
**TypeFactory.refineBounds(...) line 388:**
The old code contained two iteratores of one collections which produced under wired circumstances concurrent mocification Exception.
Tests for the new codes where added in TypeFactoryTestCase.

-----------------------------------
**Sub-Project "tests-jdk8":**
Special JDK8 Tests. e.g. with Interface default methods.
This tests also failed because of the non-optional guava-dependency.

### CODE REVIEW

**Comment by brabenetz** [comment]
After that I will get the fixes for #162 and #105 (this weekend I should have time for it)

**Comment by andreabertagnolli** [comment]
It's done? can we merge? :)

**Comment by brabenetz** [comment]
yeah! would be nice :).

**Comment by brabenetz** [comment]
Is a release 1.5.0-beta1 then possible?

**Pull request merged**
