### PR TITLE
Merge branch 1.5.x to master

### PR DESCRIPTION
**Pull request by brabenetz**
There are multiple fixes in Branch 1.5 which I merged into the master (plus fixing optional dependency to guava):

-----------------------------------
**Compile Error with JDK5:**
ma.glasnost.orika.impl.generator.VariableRef line 56 contains the call Collections.newSetFromMap(..,) which only exists since 1.6: 
https://docs.oracle.com/javase/7/docs/api/java/util/Collections.html#newSetFromMap%28java.util.Map%29

I simply updated the maven-compiler-plugin in the pom.xml line 315&316 to 1.6 (because there is no open jdk-5 issue obviously no-one use orika with jdk5):
https://github.com/brabenetz/orika/commit/c360935c779aba80cb9e02e0522eaa017eaf1a30

-----------------------------------
**Eclipse Settings folder ".settings" removed:**
most likely committed accidentally.

-----------------------------------
**Travis-CI:**
I'm not sure what the difference of the Travis-CI instances are, but I suppose that my instance is a newer container-based instance:
My Travis-CI instance: https://travis-ci.org/brabenetz/orika/builds
Orikas Travis-CI instance: https://travis-ci.org/orika-mapper/orika/builds

The Results often differ in the results.

At least for the container-based Travis-CI the following changes are required:
 - limit maven-surefire-plugin in memory: because the container based Travis-CI has only 3 GB ram which is less then the default VM. And some Memory-Consumption-Tests fills the memory with garbage to force the release of weak references.
 - set "sudo: false" in ".travis.yml" because container based Travice-CI doesn't allow sudo.

I also added openjdk6 to the build.

-----------------------------------
**Fix Optional dependency to Guava:**
ma.glasnost.orika.metadata.Type and ma.glasnost.orika.impl.DefaultConcreteTypeMap uses the guva class ImmutableMap which make Guava not optional anymore.
I refactored it with Collections.unmodifiableSet(...) and Collections.unmodifiableMap(...).
The dependency commes in with the last merge of #157 and #155: 
https://github.com/orika-mapper/orika/pull/155
https://github.com/orika-mapper/orika/pull/157

-----------------------------------
**TypeFactory.refineBounds(...) line 388:**
The old code contained two iteratores of one collections which produced under wired circumstances concurrent mocification Exception.
Tests for the new codes where added in TypeFactoryTestCase.

-----------------------------------
**Sub-Project "tests-jdk8":**
Special JDK8 Tests. e.g. with Interface default methods.
This tests also failed because of the non-optional guava-dependency.

### CODE REVIEW

**Comment by andreabertagnolli** [comment]
It makes sense support java 6, which has reached the support's end more than 3 years ago?
For the rest I'm in agreement with the whole pull request (sorry for the guava issue, I saw it into dependencies and I though it was not a problem to use it :) )

**Comment by brabenetz** [comment]
No Problem, that could happened to anybody.
I only recognized it by the additional sub-project for special jdk8-tests.

I only updated the compiler-plugin from jdk 1.5 to 1.6.
For me, jdk 7 would be also valid (I simply didn't had the guts to do that jump :D ).

**Comment by andreabertagnolli** [comment]
Anyway, what could be that error on travis' jdk6 build?
I tried to take a look but with no success

**Comment by brabenetz** [comment]
I have no clue, because I cannot reproduce it locally nor on my Travis-CI instance:
https://travis-ci.org/brabenetz/orika/builds/177276275

**Comment by brabenetz** [comment]
Is it possible to update the orika travis-ci instance to a container-based instance?

If nothing can fix the jdk6 build, the easiest way would be a fixation on minimum JDK7 version.
Only maven-compiler-plugin and travis.yml should be required to update for this.

**Comment by andreabertagnolli** [comment]
I'm trying to compare the raw logs, and on orika travis-ci log:
"This job is running on container-based infrastructure"

**Comment by andreabertagnolli** [comment]
I can't find significant differences in the logs between them...

**Comment by brabenetz** [comment]
You are right.
The test seems to be stuck in MultiThreadedTestCase.
Maybe it has something to do with #147
But this are only assumptions because I cannot reproduce it locally.

**Comment by andreabertagnolli** [comment]
I tried too, but without success...
I suggest to remove jdk6 from .travis and then merge this request, so we can go with 1.5.0 release.

Just for interest, the jdk6 was removed from the CI 4 years ago for some problems:
https://github.com/orika-mapper/orika/commit/e1415f51ac0bea0c776585514ce43611f9f35ccb

**Comment by brabenetz** [comment]
I fully agree with you.
Nice work to find the commend 4 years ago.

**Comment by brabenetz** [comment]
I will remove the jdk6 travis-ci build and provide a new pull request.

**Comment by brabenetz** [comment]
If I remove the JDK6 travis-ci build, then I will add the `animal-sniffer-maven-plugin` to validate that no newer API as available in JDK6 is used (e.g.: the use of `StandardCharsets.UTF_8` must fail, because it doesn't exist in JDK-6 ).

**Comment by andreabertagnolli** [comment]
Ok for me.

**Pull request closed without merging**
