### PR TITLE
minor code cleanups

### PR DESCRIPTION
**Pull request by 123Haynes**
removed unused imports
fixed a few warnings
replaced some deprecated methods

### CODE REVIEW

**Comment by 123Haynes** [comment]
@elaatifi I'm a bit at a loss of what to do with the usages of
https://github.com/orika-mapper/orika/blob/master/core/src/main/java/ma/glasnost/orika/MappingContext.java#L268

it's marked as deprecated, but the javadoc doesn't really suggest a replacement.
it's being used 4 times in the code base 
https://github.com/orika-mapper/orika/search?utf8=%E2%9C%93&q=beginmapping&type=

how should i replace this?

**Comment by elaatifi** [comment]
It has been replaced by beginMappingField() which keeps track of the full stack of current mapping.
We keep those kind of informations for Filters or when the context of execution is needed.
You can see that is quite heavy to keep those information. For simplest cases when this information is not needed we can choose to use a different MappingContext Factory.

Like this one : https://github.com/orika-mapper/orika/blob/master/core/src/main/java/ma/glasnost/orika/impl/NonCyclicMappingContext.java

But needs to be updated to put a No OP on every method.

**Comment by 123Haynes** [comment]
@elaatifi alright :) I'll try to replace it when I have some time in the coming days.  
I'll create a seperate PR for that.  
Meanwhile I've rebased this MR, so there shouldn't be any more merge confilcts 😄

**Comment by elaatifi** [comment]
Thank you @123Haynes  !

**Pull request merged**
