### PR TITLE
Issue 67

### LINKED ISSUE #67: NPE on VariableRef.isPrimitive() with map of map
When mapping something with a map of map, a `NullPointerException` occurs in `isPrimitive()` called by `MapToMap.generateMappingCode()`.

I think this is the same issue as reported in https://code.google.com/p/orika/issues/detail?id=170&q=NPE

See https://github.com/marcpa00/orika-issue-mapOfMap for unit tests showing the problem.

This was tested with 1.4.6.
Project above shows that a `Map<Date, Integer>` works ok, but a `Map<Date, Map<Integer, String>> ` does not.

### PR DESCRIPTION
**Pull request by andreabertagnolli**
Fix #67

### CODE REVIEW

**Comment by andreabertagnolli** [comment]
whoops, i did a mistake, will correct immediately

**Comment by elaatifi** [comment]
The Issue67TestCase still in error (duplicated variable name)

**Comment by andreabertagnolli** [comment]
yes, it works on my machine (ah!), i will look further :)

**Comment by andreabertagnolli** [comment]
incredible... I cannot replicate the test failure on my machine!
But I understand the problem, will fix it soon.

**Comment by andreabertagnolli** [comment]
Did it!

**Comment by elaatifi** [comment]
Nice many thanks !

**Pull request merged**
