### PR TITLE
Add possibility to disable destination value retrieval on mapping #301

### LINKED ISSUE #301: Default mapper executes getters on destination object
I have two classes `Source` and `Dest`. Both have getters and setters for the property `myProperty`. I've found that when I use a default mapper and map source into destination then getters from the destination object is called also (i.e. getMyProperty() is called in the `dest` object). Here is the code:
```
mapperFactory.classMap(Source.class, Dest.class).byDefault();
MapperFacade mapper = mapperFactory.getMapperFacade();
Source src = new Source("Test", 10);
Dest dest = new Dest();
mapper.map(src, dest);
```
Is there a way to prevent default mapper from calling getters on the destination object?

### PR DESCRIPTION
**Pull request by porunov**
This PR adds possibility to disable destination property value retrieval. Default behaviour isn't changed, so this PR doesn't add any breaking changes.

Possible use cases:
- Destination object getters are expensive to be executed.
- Destination object getters throws exceptions when the value isn't set yet.

Fixes #301

### CODE REVIEW

**Comment by porunov** [comment]
For some reason the test `MultiOccurrenceToMultiOccurrenceTestCase#mappingContext` is now failing. I cannot find the root problem because `getDestinationOnMapping` is always `true` in this test.

@elaatifi Do you know what could cause it? For some reason assertion on line 227 (`Assert.assertNotNull(dest);`) is failing.

**Comment by porunov** [comment]
@elaatifi found a problem with variables and fixed it. TraviCI passes for oraclejdk11. 
Failures for oraclejdk8 and oraclejdk9 isn't caused by this PR. It is currently fails in master branch.
`mvn clean install` with oraclejdk8 passes on my laptop.

**Comment by elaatifi** [comment]
No problem, will check them I think it's related to travis jdk's installers

**Comment by porunov** [comment]
@elaatifi I see you changed oraclejdk to openjdk in master but Travis still fails for openjdk 9. Should I rebase my PR from master branch / wait till Travis passes in master branch or this PR isn't necessary to be rebased?

**Comment by elaatifi** [comment]
`The command "~/bin/install-jdk.sh ..... failed" `
This error is random and on Travis side,  because of jdk.java.net is less reliable nowadays

**Pull request merged**
