### PR TITLE
enable mapping of package private classes

### PR DESCRIPTION
**Pull request by kirviq**

### CODE REVIEW

**Comment by kirviq** [comment]
solves issue https://github.com/orika-mapper/orika/issues/187

The commit contains test cases.

I tried to touch as few files as possible, but I would really like to make the usage of whitespaces and `@Override` annotation more consistent. (if this is wanted)

**Comment by brabenetz** [comment]
Thanks for the contribution, but it seams that it's only a start.
The main reason for this are the fact that all existing TestCases works with public classes.
No test will pop up when something doesn't work with package-default visibility.
In other words: It's a complete new frontier where no one has gone before. :D

The attached Tests shows that generated ObjectFactories or Nested Classes seams not to work with package-default visibility.
[Issue-189_orika-package-private_ptoblems.patch.txt](https://github.com/orika-mapper/orika/files/752616/Issue-189_orika-package-private_ptoblems.patch.txt)

About Analysis.getMostRestrictiveVisibility():
I think `default` (package private) visibility is more restricted than `protected`:
http://stackoverflow.com/a/215505/702345
So, everything which works with Visibility.PACKAGE should also work with Visibility.PROTECTED.

**Comment by kirviq** [comment]
I added/fixed these two cases. (pushed to my fork on https://github.com/kirviq/orika/)
The assumption that all mapped classes are public permeates throughout the entire code. Code that I don't know all that well. If you can think of more cases that should be tested I'm happy to add tests for them.

I had some issues with the test `MultiLayeredClassloader_IDEOnly`. I replaced the manual temp directory creation with a JUnit TemporaryFolder Rule to ensure the directory is deleted after test run and haven't had any issues with this test ever since. Not sure if this solves the instabilities mentioned in the comment.

To be honest I haven't given any thought about protected classes or fields. The linked table on stackoverflow is not entirely correct. Being in the same package is not sufficient to access protected. So any mapping class that we generate for this would have to be a subclass of the protected class' parent and I don't think we want to go that way.

**Comment by kirviq** [comment]
I was honestly not aware that you can access protected stuff just by being in the same package. You learn something new every day.

Works now too.

**Comment by brabenetz** [comment]
Looks great.
I think you need a new pull request.

**Pull request merged**
